apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: resources-creator-binding
  # namespace: user-1-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: resources-creator
subjects:
- kind: ServiceAccount
  name: resources-creator-sa
  # namespace: my-namespace