apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app01
  namespace: argocd
spec:
  project: default
  source:
    path: 290_gitops_argocd/kubernetes
    repoURL: https://github.com/HoussemDellai/aks-course
    targetRevision: HEAD
  destination:
    namespace: webapp
    server: https://kubernetes.default.svc